### ISSUE TITLE
client-influx.py: issue while dhcp 

### ISSUE THREAD

**Issue by lemoer** [mdmdmdmdmd/pygatemon#3]
```
Traceback (most recent call last):
  File "client-influx.py", line 135, in <module>
    main()
  File "client-influx.py", line 127, in main
    points.append(create_json(tester, 'dhcp', name, check_dhcp(device, check4.format(node))))
  File "client-influx.py", line 82, in check_dhcp
    dhcp_offer = srp1(dhcp_discover, timeout=5, verbose=False)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 385, in srp1
    a,b=srp(*args,**kargs)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 368, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 141, in sndrcv
    h = r.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/l2.py", line 142, in hashret
    return struct.pack("H",self.type)+self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/inet6.py", line 428, in hashret
    return struct.pack("B",nh)+self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/packet.py", line 742, in hashret
    return self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/inet6.py", line 1325, in hashret
    return struct.pack("HH",self.mladdr)+self.payload.hashret()
struct.error: pack expected 2 items for packing (got 1)
```

I'll look further, what's wrong.

**Comment by lemoer** [comment]
Seems to happen when trying to test sn04 currently. sn04 is not available/online at the moment. After removing sn04, it works again.

**Comment by lemoer** [comment]
(minor bug)

**Comment by lemoer** [comment]
Hm. Seems to happen again:
```
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
sn01
sn07
Traceback (most recent call last):
  File "client-influx.py", line 135, in <module>
    main()
  File "client-influx.py", line 127, in main
    points.append(create_json(tester, 'dhcp', name, check_dhcp(device, check4.format(node))))
  File "client-influx.py", line 82, in check_dhcp
    dhcp_offer = srp1(dhcp_discover, timeout=5, verbose=False)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 385, in srp1
    a,b=srp(*args,**kargs)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 368, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/sendrecv.py", line 141, in sndrcv
    h = r.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/l2.py", line 142, in hashret
    return struct.pack("H",self.type)+self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/inet6.py", line 428, in hashret
    return struct.pack("B",nh)+self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/packet.py", line 742, in hashret
    return self.payload.hashret()
  File "/root/pygatemon/env/lib/python3.5/site-packages/scapy/layers/inet6.py", line 1325, in hashret
    return struct.pack("HH",self.mladdr)+self.payload.hashret()
struct.error: pack expected 2 items for packing (got 1)

```

**Comment by lemoer** [comment]
(but not every time)
